### ISSUE TITLE
Elastic Beanstalkのチュートリアルでエラーが出る

### ISSUE THREAD

**Issue by Yusuke196** [Yusuke196/significant_or_not#5]
EBの使い方の参考にするため以下のチュートリアルを進めているが、

- Elastic Beanstalk への Django アプリケーションのデプロイ - AWS Elastic Beanstalk
https://docs.aws.amazon.com/ja_jp/elasticbeanstalk/latest/dg/create-deploy-python-django.html

「EB CLI でサイトをデプロイする」の作業をすべて終えたところで、アプリケーションが正常にデプロイされていることを確認できない。

ブラウザで確認するとレスポンスは502 Bad Gatewayとなっており、ログ（最後の100行）は以下。
[eblog.txt](https://github.com/Yusuke196/significant_or_not/files/6871849/eblog.txt)

使ったディレクトリは以下。
[app-210723_110959.zip](https://github.com/Yusuke196/significant_or_not/files/6866503/app-210723_110959.zip)

ちなみに完全にチュートリアルのとおりにやろうとすると
Python 3.6 running on 64bit Amazon Linux/2.10.2というプラットフォームを使うことになるが、
これは非推奨らしいので、上では3.8を使った。
3.6を使うパターンも試したが、やはりエラーが出た。

@imony こちらの件なのですが、原因が分からないためアドバイスいただけないでしょうか？

**Comment by imony** [comment]
@Yusuke196 原因を調査してみました。

# 起きているエラーの詳細について
端的にいうとDjangoが起動できていません。

ログファイルから読み取りますと、
```log:/var/log/web.stdout.log
Jul 23 03:11:30 ip-172-31-26-80 web: ModuleNotFoundError: No module named 'ebdjango'
```

ここが原因と推察します。deploy後にDjangoを起動しようとしましたが、上記エラーによりDjangoの起動に失敗しております。一方で、nginxは起動に成功したのでWebサーバーとしてブラウザからのリクエストを受ける用意はできています。
nginxはブラウザからのHTTPリクエストを受け付けます。受け付けたリクエストがDjangoへ転送すべきものであった場合にDjangoに転送処理を行います。ここでnginxは、転送先に指定されているDjangoが起動していないことに気づきます。そのためnginxはブラウザに502 Bad Gatewayレスポンスを返します。


# どこに原因があるか
.ebextensions/django.config ファイルには以下のように設定が記述されています。
```
option_settings:
  aws:elasticbeanstalk:container:python:
    WSGIPath: ebdjango.wsgi:application
```

これは、nginxにDjangoアプリケーションを起動するためのエントリーポイントをWSGIPathとして指定しています。指定されている値は ebdjango.wsgi です。これはebdjangoディレククトリ下のwsgi.pyファイルを指定しています。

一方で、デプロイに使ったディレクトリのzipファイルを解凍して見てみますと、ebdjangoディレクトリが存在しません（代わりにebdjango2ディレクトリが存在しています）。この部分がdeploy後にDjangoを起動してもエラーとなる原因と思われます。

# どう対処すべきか
２通りあると思います。
- .ebextensions/django.configを書き換える（実際のディレクトリ構成に合わせる）
- ディレクトリ構成を変える（.ebextensions/django.configの設定に合わせる）
チュートリアルに従うのであれば後者を取るのが良いのではないかと思います。

**Comment by Yusuke196** [comment]
@imony 詳細なフィードバックありがとうございます。

おっしゃるとおり、ディレクトリの名前とdjango.configで指定したパスが違っていることが原因だったようで、
django.configを書き換えることで解消できました。
