### ISSUE TITLE
docker-composeで管理されたDjangoのプロジェクトをBeanstalkにデプロイできない

### ISSUE THREAD

**Issue by Yusuke196** [Yusuke196/significant_or_not#6]
## やりたいこと

以下のステップを踏んで作成したDjango + Postgresの2コンテナをBeanstalkで動かしたい。
- Dockerfile, docker-compose.yml, requirements.txt, .gitignoreを用意
- docker-compose run web django-admin startproject <project>を実行
- settings.pyを編集してdbをpostgresqlに指定

まずは手元でサンプルを作って試し、上手くいったらそれを実際に今回のシステムに適用したい。

## エラー概要

Dockerfileとdocker-compose.ymlを含む、次のようなディレクトリを用意し、
[eb_docker_django_2.zip](https://github.com/Yusuke196/significant_or_not/files/6889771/eb_docker_django_2.zip)

このディレクトリのルートで`eb init -p docker eb-django`と`eb create eb-django-env`を実行したところ、次のようなエラーが出た。
```
$ eb init -p docker eb-django
Application eb-django has been created.
$ eb create eb-django-env
Creating application version archive "app-210727_183707".
Uploading eb-django/app-210727_183707.zip to S3. This may take a while.
Upload Complete.
Environment details for: eb-django-env
  Application name: eb-django
  Region: us-west-2
  Deployed Version: app-210727_183707
  Environment ID: e-rm9kx9fcek
  Platform: arn:aws:elasticbeanstalk:us-west-2::platform/Docker running on 64bit Amazon Linux 2/3.4.3
  Tier: WebServer-Standard-1.0
  CNAME: UNKNOWN
  Updated: 2021-07-27 09:37:12.021000+00:00
Printing Status:
2021-07-27 09:37:10    INFO    createEnvironment is starting.
2021-07-27 09:37:12    INFO    Using elasticbeanstalk-us-west-2-448211181166 as Amazon S3 storage bucket for environment data.
2021-07-27 09:37:32    INFO    Created security group named: sg-0e34006d9c020a18e
2021-07-27 09:37:32    INFO    Created load balancer named: awseb-e-r-AWSEBLoa-68GSGDQT3FE3
2021-07-27 09:37:49    INFO    Created security group named: awseb-e-rm9kx9fcek-stack-AWSEBSecurityGroup-UKNVTN46JB2G
2021-07-27 09:37:49    INFO    Created Auto Scaling launch configuration named: awseb-e-rm9kx9fcek-stack-AWSEBAutoScalingLaunchConfiguration-H8FUX5W5DPZA
2021-07-27 09:39:06    INFO    Created Auto Scaling group named: awseb-e-rm9kx9fcek-stack-AWSEBAutoScalingGroup-1IYYLNWBXGPX9
2021-07-27 09:39:06    INFO    Waiting for EC2 instances to launch. This may take a few minutes.
2021-07-27 09:39:06    INFO    Created Auto Scaling group policy named: arn:aws:autoscaling:us-west-2:448211181166:scalingPolicy:755b8423-dc12-4452-af61-add1da6e187b:autoScalingGroupName/awseb-e-rm9kx9fcek-stack-AWSEBAutoScalingGroup-1IYYLNWBXGPX9:policyName/awseb-e-rm9kx9fcek-stack-AWSEBAutoScalingScaleUpPolicy-VV8R40F2RHDR
2021-07-27 09:39:06    INFO    Created CloudWatch alarm named: awseb-e-rm9kx9fcek-stack-AWSEBCloudwatchAlarmLow-3DMFLFZGOENQ
2021-07-27 09:39:06    INFO    Created CloudWatch alarm named: awseb-e-rm9kx9fcek-stack-AWSEBCloudwatchAlarmHigh-1MNT0XVDC8Q9V
2021-07-27 09:39:26    ERROR   Instance deployment failed. For details, see 'eb-engine.log'.
2021-07-27 09:39:28    ERROR   [Instance: i-0f78721ab95414a1e] Command failed on instance. Return code: 1 Output: Engine execution has encountered an error..
2021-07-27 09:39:28    INFO    Command execution completed on all instances. Summary: [Successful: 0, Failed: 1].
2021-07-27 09:40:30    ERROR   Create environment operation is complete, but with errors. For more information, see troubleshooting documentation.

ERROR: ServiceError - Create environment operation is complete, but with errors. For more information, see troubleshooting documentation.
```

ログを見ると以下のような表示がある。
```
----------------------------------------
/var/log/eb-docker/containers/eb-current-app/eb-stdouterr.log
----------------------------------------
Attaching to 
Attaching to current_web_1, current_db_1
current_db_1 exited with code 1
current_web_1 exited with code 2
db_1   | 
db_1   | 2021-07-27 15:24:38.666 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 12, which is not compatible with this version 13.3 (Debian 13.3-1.pgdg100+1).
db_1   | 2021-07-27 15:24:38.666 UTC [1] FATAL:  database files are incompatible with server
db_1   | PostgreSQL Database directory appears to contain a database; Skipping initialization
web_1  | python: can't open file '/code/manage.py': [Errno 2] No such file or directory
```

**Comment by Yusuke196** [comment]
調査のためsshでEC2インスタンスの中に入って見ると、
webappディレクトリに何か入っていそうだが、開く権限がない。

```
[ec2-user@ip-172-31-2-205 ~]$ pwd
/home/ec2-user
[ec2-user@ip-172-31-2-205 ~]$ cd ..
[ec2-user@ip-172-31-2-205 home]$ ls
ec2-user  healthd  webapp
[ec2-user@ip-172-31-2-205 home]$ ls webapp/
ls: ディレクトリ webapp/ を開くことが出来ません: Permission denied
```

**Comment by Yusuke196** [comment]
Web上にある情報は、多くが既に非推奨となったAMIで動く、マルチコンテナDockerプラットフォームを利用する方法を採用している（たとえば以下）。

- Rails, Dockerで動くアプリをAWS Elastic Beanstalkにデプロイするまでの全て - Qiita
https://qiita.com/kota-shidara/items/665fa02f360d42ff8435

いま自分はAmazon Linux 2を使おうとしているが、その場合、マルチコンテナDockerプラットフォームは使えない。

**Comment by imony** [comment]
まずエラーの原因を探りたいと思います。
```bash
$ eb create eb-django-env
```
上記実行時のエラーメッセージに以下の記述を見つけました。
> 2021-07-27 09:39:26    ERROR   Instance deployment failed. For details, see 'eb-engine.log'.

エラーの詳細が'eb-engine.log'にあるようですので、こちらも見せていただけますと大変助かります。

また、/var/log/eb-docker/containers/eb-current-app/eb-stdouterr.log のログに以下の記述がございます。
> web_1  | python: can't open file '/code/manage.py': [Errno 2] No such file or directory

これはデプロイに失敗しているために /code/manage.py ファイルがまだ存在せず、webコンテナでdjangoを起動しようとした際にエラーになっています。これはdjango起動時のエラーですが、根本の原因はデプロイに失敗している点です。この原因を探ると問題解消に繋がると思います。

-----
まずは、eb-engine.log のエラーメッセージを確認し、より具体的なエラーの理由を探りたく存じます。情報のご提供よろしくお願いいたします。

-----
もう一点、お願いがございます。
eb_docker_django_2.zip の中身が空のようでしたので、お手隙の際に再度ご提供いただけますようお願いいたします。

**Comment by Yusuke196** [comment]
> エラーの詳細が'eb-engine.log'にあるようですので、こちらも見せていただけますと大変助かります。

失礼しました。eb-engine.logを含むログ全体を、以下に貼り付けたのでご確認お願いいたします。

[eb_docker_django.log](https://github.com/Yusuke196/significant_or_not/files/6893070/eb_docker_django.log)

何度かBeanstalkの環境を作り直している関係で、上に貼ったeb-stdouterr.logとは日時が変わっていますが、状態としては大きく変化していないかと思います。

> eb_docker_django_2.zip の中身が空のようでしたので、お手隙の際に再度ご提供いただけますようお願いいたします。

すみません、こちらになります。お願いします。 @imony 

[eb_docker_django_2.zip](https://github.com/Yusuke196/significant_or_not/files/6893099/eb_docker_django_2.zip)

**Comment by imony** [comment]
@Yusuke196 ログ、及びデプロイ構成をご提供いただきましてありがとうございます。確かに頂戴しました。
ログ、設定ファイル、デプロイ構成を精査して、原因を調査してまいります。
調査には少しお時間を頂けますと幸いです。
どうぞよろしくお願いいたします。

**Comment by imony** [comment]
@Yusuke196 
docker-compose.yml に以下の記述がございます。
```
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
```
volumesの設定を見ると、docker-compose.ymlファイルが存在するディレクトリをwebコンテナの/codeディレクトリにマウントされておられます。となると、webコンテナから見た場合のmanage.pyファイルの絶対パスは
> /code/proj/manage.py

となります。

ここでエラーメッセージの内容を思い出すと、次の一文がございました。
/var/log/eb-docker/containers/eb-current-app/eb-stdouterr.log より
> web_1 | python: can't open file '/code/manage.py': [Errno 2] No such file or directory

このエラーは、webコンテナ上の/codeディレクトリをカレントワーキングディレクトリ（現在の作業ディレクトリ）としてコマンド
python manage.py runserver 0.0.0.0:8000
を実行しようとしたために、manage.pyファイルがカレント

**Comment by Yusuke196** [comment]
ありがとうございます。頂いたコメントを元に自分の行っていた操作を見返したところ、
`docker-compose run web django-admin startproject`を実行する時に、
ディレクトリの指定でミスしていたことが分かりました。

そこで、その点を修正した次のようなディレクトリを作成して
[eb_docker_django_3.zip](https://github.com/Yusuke196/significant_or_not/files/6908200/eb_docker_django_3.zip)
手元でdocker-compose upを試し、きちんとwebおよびdbコンテナが立ち上がることを確認しました（ご提案いただいたものと解決策は違ってしまい恐縮なのですが、[Dockerの公式](https://docs.docker.com/samples/django/)で紹介されているディレクトリ構成に寄せて進めたいため）。

ただ、これを`eb deploy`としてデプロイすると、dbとweb両方のコンテナでエラーが出ました。

`/var/log/eb-docker/containers/eb-current-app/eb-stdouterr.log`を見ると、dbの方では
```
db_1   | 2021-07-30 02:19:44.790 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 12, which is not compatible with this version 13.3 (Debian 13.3-1.pgdg100+1).
current_db_1 exited with code 1
```
webの方では
```
web_1  | django.db.utils.OperationalError: could not translate host name "db" to address: Name or service not known
```
というエラーが出ています。

まずdbの方のエラーに注目して考えると、バージョンがずれてしまうことが原因のもよう。ちなみに手元のdbコンテナでpostgresのバージョンを調べると、
```
root@d5f47a7ec747:/# psql --version
psql (PostgreSQL) 12.3 (Debian 12.3-1.pgdg100+1)
```
となる。

そこで、docker-compose.ymlに
```
services:
  db:
    image: postgres:12
```
という形でバージョンの指定`:12`を追加してみました。こうしてdocker-compose upしなおすと、手元のdbコンテナのバージョンは12.2に変わりました。

ここでeb deployとしてからbeanstalkのログを確認すると、
```
Attaching to current_web_1, current_db_1
db_1   | 
db_1   | PostgreSQL Database directory appears to contain a database; Skipping initialization
db_1   | 
db_1   | 2021-07-31 02:57:03.351 UTC [1] LOG:  starting PostgreSQL 12.7 (Debian 12.7-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
db_1   | 2021-07-31 02:57:03.353 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db_1   | 2021-07-31 02:57:03.353 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db_1   | 2021-07-31 02:57:03.356 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1   | 2021-07-31 02:57:03.382 UTC [1] LOG:  could not open directory "pg_tblspc": No such file or directory
db_1   | 2021-07-31 02:57:03.386 UTC [25] LOG:  database system was interrupted; last known up at 2021-07-31 02:53:11 UTC
db_1   | 2021-07-31 02:57:03.386 UTC [25] LOG:  creating missing WAL directory "pg_wal/archive_status"
db_1   | 2021-07-31 02:57:03.410 UTC [25] LOG:  could not open directory "pg_tblspc": No such file or directory
db_1   | 2021-07-31 02:57:03.411 UTC [25] LOG:  could not open directory "pg_tblspc": No such file or directory
db_1   | 2021-07-31 02:57:03.411 UTC [25] FATAL:  could not open directory "pg_replslot": No such file or directory
db_1   | 2021-07-31 02:57:03.418 UTC [1] LOG:  startup process (PID 25) exited with exit code 1
db_1   | 2021-07-31 02:57:03.418 UTC [1] LOG:  aborting startup due to startup process failure
db_1   | 2021-07-31 02:57:03.420 UTC [1] LOG:  database system is shut down
```
となり、やはりdbコンテナが起動できませんでした（エラー全文は以下）。
[eb.log](https://github.com/Yusuke196/significant_or_not/files/6910583/eb.log)

また、dbコンテナのimageを`postgres:13`にするパターンも試してみました（どちらのバージョンを使いたいかについて、自分にはこだわりはないので）。

まず（PostgreSQL version 12でinitializeされたdataディレクトリを削除した上で）手元でdocker-compose upしなおすと、無事にコンテナを立ち上げることができて、psqlのバージョンが13.3となっていることも確認できました。

そこで`eb deploy`としてログを確認すると、以下の結果になっていました。
```
Attaching to current_web_1, current_db_1
db_1   | 
db_1   | PostgreSQL Database directory appears to contain a database; Skipping initialization
db_1   | 
db_1   | 2021-07-31 03:19:37.245 UTC [1] FATAL:  could not open directory "pg_notify": No such file or directory
db_1   | 2021-07-31 03:19:37.246 UTC [1] LOG:  database system is shut down
```
バージョンを12に指定したときと比べるとエラーは減っていますが、やはり何らかの問題が出ているようです。

散らかったメモですみませんが、このあたり、もしアドバイスあればいただけたらありがたいです。。 @imony

**Comment by imony** [comment]
@Yusuke196 
現在お困りの点、拝読いたしました！
webとdbでエラーとなる点は把握いたしましたが、原因を探るのにお時間をいただけますと幸いです。docker-composeなど設定ファイルに何か齟齬があるのではないかと踏んでおりますが、原因を突き止めますまで今しばらくお待ちください。

**Comment by imony** [comment]
@Yusuke196 
docker-compose.yml の設定を抜粋します。
```
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
 ```
設定を見ると、 volumesで、ローカルの./data/dbディレクトリをdbコンテナの/var/lib/postgresql/dataディレクトリとしてマウントするように設定されています。おそらくですが、./data/dbディレクトリはローカルで動かしているpostgresqlのディレクトリのデータが入っていて、それそのままdbコンテナのデータベースディレクトリとして使おうとしたのではないでしょうか。これがエラーの原因となっているように思われます。

ローカルで使っていたpostgresqlのデータベースをそのままdbコンテナで使える想定でそうなさったのだと推察しますが、流用はしない方が無難です。ローカルの何もない空の ディレクトリを別途用意して、それをdbコンテナの/var/lib/postgresql/dataとしてマウントしてあげるのが良いと思います。

理由としては、例えpostgresqlのバージョンが同じであってもOSが異なる場合は違いが生じ得るためです（実際、異なっていると思えるエラーメッセージになっています）。dbコンテナのimageにversion13のpostgresqlを利用した場合は、データベースのディレクトリにすでにversion12で作成したデータが入っているため、不整合を検知してエラーとなっています。

解決方法の提案としては、ローカルで新たなディレクトリを作成して、それをdbコンテナの/var/lib/postgresql/dataにマウントしてあげることをおすすめします。dbコンテナのpostgresqlバージョンについては、最新の13を使うのが良いでしょう（特に12にバージョンダウンしたい理由がなければ）。dbコンテナが立ち上がれば、/var/lib/postgresql/dataディレクトリが空なのを検知したらversion13のデータを生成・格納してくれます（Djangoのmake migrations / migrateコマンドでモデルに対応したテーブル等が作成されるので、このコマンドの実行もお忘れなく）。

上記、お試しいただけますと幸いです。
どうぞよろしくお願いいたします。

**Comment by Yusuke196** [comment]
> 解決方法の提案としては、ローカルで新たなディレクトリを作成して、それをdbコンテナの/var/lib/postgresql/dataにマウントしてあげることをおすすめします。

すみません、自分の認識では、この操作は一つ前のコメントの時点で実行していた「PostgreSQL version 12でinitializeされたdataディレクトリを削除」という操作と同じ結果、つまり

> dbコンテナが立ち上がれば、/var/lib/postgresql/dataディレクトリが空なのを検知したらversion13のデータを生成・格納してくれます

ということになるのではと思っていますが、その理解は違っているでしょうか？

また、ここでおっしゃっているのは、上記のようにすればeb deployが上手くいくということでしょうか？

よろしくお願いします。。

**Comment by imony** [comment]
@Yusuke196 
はい、理解はあっております。
./data/dbディレクトリが空であれば、dbコンテナが立ち上がった時に./data/db（dbコンテナから見ると/var/lib/postgresql/data）にデータベースに必要なファイルが作成されます。
私はすでに何かしらのデータが入っている./data/dbディレクトリをマウントしたためエラーが生じたと思ったのですが、実際は空のディレクトリをマウントされていたのでしょうか？そうなると原因は別なところにありそうな気がいたします。

eb_docker_django_3.zip を解凍してdata/db/PG_VERSIONをみたところ、12との記述がございましたため、すでにversion12 のpostgresqlでデータを作成したディレクトリをマウントしたのかな、と思った次第でした。

空のディレクトリをマウントしてあげれば、dbコンテナの起動時にデータベースはうまく作成されると思います（つまり、dbコンテナの準備はできた、と言える）。もしかしたら、そこがクリアできたとしてもその先（例えば、dbコンテナとwebコンテナの連携など）にまた別な原因でエラーが生じるかもしれませんが、少なくとも一歩進む状態にはなるかと存じます。

**Comment by Yusuke196** [comment]
一度Beanstalkの環境をすべて消した上で、以下の順序でやりなおしたところ、エラーメッセージが変わりました。

1. dataディレクトリを削除する
2. eb create

確かに、`could not open directory "pg_xxxx"のようなエラーは出なくなりました。
（エラー全文は以下）
https://www.notion.so/yusuke196/25e06ea3b2fe408b98dcc83178a91e05#7252d80a9a874961ab1c526c44ffaca9

ただ、適用されていないマイグレーションがあるから、python manage.py migrateしてね、というメッセージが出ているので、これに対処することを考えます。

［以下、メモ］dataディレクトリをeb deployの際にignoreするということができればよさそうだが、その方法が分からない。dataディレクトリをgitignoreしておいて、GitHubにdataを除くディレクトリをアップロードすると、そこから自動でBeanstalkにデプロイされるという構成ができるとよいかも。

とりあえず、docker-compose.ymlを書き直してdataディレクトリをマウントするのを止めてcompose upし、マイグレーションを適用してからeb deployしてみた。が、eb-stdouterr.logの内容は変わらなかった。

eb sshでEC2インスタンスの中に入ってpython manage.py migrateとすればエラーを解消できるのではと考えて、ssh接続の環境を整えてみる。

**Comment by Yusuke196** [comment]
まず、いま使っているeb-django-env-3という環境のヘルスのページで初期の状態を確認すると、以下のようにインスタンスが一つある。

![image](https://user-images.githubusercontent.com/20034398/128586780-905fd137-6159-4edb-9de3-a8026089f6d1.png)

この状態から手元のターミナルでeb sshとすると、`ERROR: This environment is not set up for SSH. Use "eb ssh --setup" to set up SSH for the environment.`と表示されるので、以下のようにする。
```
$ eb ssh --setup
WARNING: You are about to setup SSH for environment "eb-django-env-3". If you continue, your existing instances will have to be **terminated** and new instances will be created. The environment will be temporarily unavailable.
To confirm, type the environment name: eb-django-env-3

Select a keypair.
1) aws-eb
2) [ Create new KeyPair ]
(default is 1):

Printing Status:
2021-08-07 03:39:21    INFO    Environment update is starting.
2021-08-07 03:39:28    INFO    Updating environment eb-django-env-3's configuration settings.
2021-08-07 03:39:44    INFO    Created Auto Scaling launch configuration named: awseb-e-djpu4qrdfy-stack-AWSEBAutoScalingLaunchConfiguration-1111435QHUVLQ
2021-08-07 03:40:00    INFO    Auto Scaling group update progress: Rolling update initiated. Terminating 1 obsolete instance(s) in batches of 1, while keeping at least 1 instance(s) in service. Waiting on resource signals with a timeout of PT30M when new instances are added to the autoscaling group.
2021-08-07 03:40:00    INFO    Auto Scaling group update progress: Temporarily setting autoscaling group MinSize and DesiredCapacity to 2.
2021-08-07 03:41:33    INFO    Auto Scaling group update progress: New instance(s) added to autoscaling group - Waiting on 1 resource signal(s) with a timeout of PT30M.

ERROR: TimeoutError - The EB CLI timed out after 5 minute(s). The operation might still be running. To keep viewing events, run 'eb events -f'. To set timeout duration, use '--timeout MINUTES'.
```

すると、インスタンスがもうひとつできる。
![image](https://user-images.githubusercontent.com/20034398/128586863-dd7be003-2160-41ce-95ca-268cd05dfd31.png)

しかしこの後しばらく待つと、新しくできたインスタンスは消えてしまい、その状態で手元のターミナルで`eb ssh`としても`ERROR: This environment is not set up for SSH.`という以前と同じエラーが出てしまう。

**Comment by Yusuke196** [comment]
［メモ］上記のエラーを解消するには、以下の手続きが必要だった。

- webコンテナでEC2側の80番ポートをコンテナ側の8000番ポートにつなぐ。
- docker-compose.ymlのwebのcommandで、runserverの前にmanage.py migrateする（[参考](https://genzouw.com/entry/2020/01/28/120014/1910/)）。
- ALLOWED_HOSTSにBeanstalkのホスト名を追加する。

こうすると、起動したEC2インスタンスにssh接続することもできるようになった。

**Comment by Yusuke196** [comment]
その後、EC2のインスタンスについて、以下のことが分かった。

1. docker-compose.ymlなどのアップロードされたファイルは、EC2インスタンス内では/var/app/currentに格納される。

1. EC2インスタンス内でdockerやdocker-composeを使うためには、sudoをつけるか、ec2-userがdockerを実行できるように権限を設定する必要がある。
- 前者の方法だと、以下のようにしてdockerコンテナが起動していることを確認できる。
```
[ec2-user@ip-172-31-41-141 current]$ sudo docker-compose ps
    Name                   Command               State          Ports
-----------------------------------------------------------------------------
current_db_1    docker-entrypoint.sh postgres    Up      5432/tcp
current_web_1   bash -c python manage.py m ...   Up      0.0.0.0:80->8000/tcp
```
- 後者の方法だと、`sudo usermod -a -G docker $(whoami)`とすると、whoamiのところがec2-userに置き換わり、ec2-userのセカンダリーグループをdockerに設定できる。-aすなわちappendオプションをつけることで、セカンダリーグループの変更ではなく追加がなされる。この操作により、なぜかec2-userでログインしていてもdockerコマンドを実行できるようになる（入っているグループと同名のコマンドは打つ権限が与えられる、ということかも）。

**Comment by Yusuke196** [comment]
最終的なサンプル環境eb-django-env-3の設定は、以下のとおり。

![image](https://user-images.githubusercontent.com/20034398/133885811-aac0f6a1-d663-4fe1-84a9-903ef4591fcb.png)

この記録を作成後、課金を避けるため再度環境eb-django-env-3は終了した。
